# Generated by Django 5.2.17 on 2026-09-08 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('hotel', '0002_property_roomtype_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='home_property',
            field=models.ForeignKey(blank=True, help_text='Home hotel for staff; blank = chain-wide (head office)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='hotel.property'),
        ),
    ]
