# Generated by Django 5.2.17 on 2026-09-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_home_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='welcome_offer_used',
            field=models.BooleanField(default=False, help_text='10% first-stay welcome offer has been consumed'),
        ),
    ]
