# Generated by Django 5.2.17 on 2026-10-01 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_welcome_offer_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('guest', 'Guest'), ('receptionist', 'Receptionist'), ('housekeeping', 'Housekeeping'), ('manager', 'Group Manager'), ('property_manager', 'Property Manager'), ('admin', 'Administrator')], default='guest', max_length=20),
        ),
    ]
