# Generated by Django 5.2.17 on 2026-09-08 09:11

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('icon', models.CharField(default='✦', help_text='Short glyph shown in UI', max_length=8)),
            ],
            options={
                'verbose_name_plural': 'amenities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Nightly rack rate before rules/taxes.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('max_guests', models.PositiveSmallIntegerField(default=2)),
                ('total_rooms', models.PositiveSmallIntegerField(default=1, help_text='Physical inventory of this type')),
                ('size_sqm', models.PositiveSmallIntegerField(default=30)),
                ('floor_range', models.CharField(blank=True, help_text='e.g. 3–8', max_length=32)),
                ('bed_type', models.CharField(choices=[('king', '1 King Bed'), ('twin', '2 Twin Beds'), ('double', '1 Double Bed'), ('suite', 'King + Living Area')], default='king', max_length=16)),
                ('image_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('cancellation_days', models.PositiveSmallIntegerField(default=2, help_text='Free cancellation up to N days before arrival')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amenities', models.ManyToManyField(blank=True, to='hotel.amenity')),
            ],
            options={
                'ordering': ['base_price', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=12, unique=True)),
                ('floor', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('vacant_clean', 'Vacant · Clean'), ('vacant_dirty', 'Vacant · Dirty'), ('occupied_clean', 'Occupied · Clean'), ('occupied_dirty', 'Occupied · Dirty'), ('maintenance', 'Under Maintenance'), ('out_of_order', 'Out of Order')], default='vacant_clean', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='room_set', to='hotel.roomtype')),
            ],
            options={
                'ordering': ['floor', 'number'],
            },
        ),
    ]
