# Generated by Django 5.2.17 on 2026-09-08 12:27

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('tagline', models.CharField(blank=True, max_length=160)),
                ('description', models.TextField(blank=True)),
                ('city', models.CharField(max_length=80)),
                ('country', models.CharField(default='Cambodia', max_length=80)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('stars', models.PositiveSmallIntegerField(choices=[(3, '3★'), (4, '4★'), (5, '5★')], default=5)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('service_rate', models.DecimalField(decimal_places=3, default=Decimal('0.050'), help_text='Service charge, e.g. 0.050 = 5%', max_digits=4)),
                ('tax_rate', models.DecimalField(decimal_places=3, default=Decimal('0.100'), help_text='VAT/GST on rooms+service, e.g. 0.100 = 10%', max_digits=4)),
                ('check_in_hour', models.PositiveSmallIntegerField(default=14)),
                ('check_out_hour', models.PositiveSmallIntegerField(default=12)),
                ('image_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'properties',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='roomtype',
            name='property',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='room_types', to='hotel.property'),
            preserve_default=False,
        ),
    ]
