# Generated by Django 5.2.17 on 2026-09-08 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_property_roomtype_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='hotel.property'),
        ),
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.CharField(help_text='Unique within its property', max_length=12),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('property', 'number'), name='unique_room_number_per_property'),
        ),
    ]
