# Generated by Django 5.2.17 on 2026-09-09 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_room_property_alter_room_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='vibe_tags',
            field=models.CharField(blank=True, default='', help_text="Comma-separated destination categories, e.g. 'Temples, History, Culture'", max_length=160),
        ),
    ]
