# Generated by Django 5.2.17 on 2026-09-09 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_property_vibe_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('blurb', models.CharField(blank=True, max_length=200)),
                ('icon', models.CharField(default='📍', max_length=8)),
                ('distance', models.CharField(blank=True, max_length=24)),
                ('sort', models.PositiveSmallIntegerField(default=0)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attractions', to='hotel.property')),
            ],
            options={
                'ordering': ['sort', 'name'],
            },
        ),
    ]
