# Generated by Django 5.2.17 on 2026-09-09 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_attraction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenity',
            name='icon',
            field=models.CharField(default='✦', help_text='Short glyph shown in UI', max_length=40),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='icon',
            field=models.CharField(default='ri-map-pin-2-line', max_length=40),
        ),
    ]
