# Generated by Django 5.2.17 on 2026-09-09 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_alter_amenity_icon_alter_attraction_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenity',
            name='icon',
            field=models.CharField(default='ri-vip-diamond-line', help_text='Remix Icon class shown in UI', max_length=40),
        ),
    ]
