# Generated by Django 5.2.17 on 2026-09-21 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_alter_amenity_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attraction',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='latitude',
            field=models.FloatField(blank=True, help_text='WGS-84 decimal degrees (Google Maps source)', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='longitude',
            field=models.FloatField(blank=True, help_text='WGS-84 decimal degrees (Google Maps source)', null=True),
        ),
    ]
