# Generated by Django 5.2.17 on 2026-09-28 09:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_attraction_latitude_attraction_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='service_rate',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Service charge; default 0% because the Cambodia demo uses tax only', max_digits=4),
        ),
        migrations.AlterField(
            model_name='property',
            name='tax_rate',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.050'), help_text='VAT/GST, e.g. 0.050 = 5%', max_digits=4),
        ),
    ]
