"""Build a current MySQL/MariaDB Navicat script without a MySQL server.

The regular export_navicat_kit.py creates authoritative vendor dumps by
migrating scratch PostgreSQL/MySQL databases. This companion is useful on a
Windows workstation before MySQL is installed: Django's MySQL schema editor
collects the current migration SQL offline, and the live SQLite rows are
rendered as portable INSERT statements.

Usage:
    python scripts/export_mysql_kit_offline.py
"""
from __future__ import annotations

import os
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "config.settings")
os.environ.setdefault("NAVICAT_DDL_VENDOR", "mysql")
os.environ.setdefault("NAVICAT_DDL_NAME", "aurelia")

import django  # noqa: E402

django.setup()

from django.db import connections  # noqa: E402
from django.db.migrations.loader import MigrationLoader  # noqa: E402
from django.db.migrations.state import ProjectState  # noqa: E402

# Reuse the tested FK-topological row renderer from the main exporter.
from scripts.export_navicat_kit import data_sql  # noqa: E402
from django.db.backends.base.schema import BaseDatabaseSchemaEditor  # noqa: E402
from django.db.backends.mysql.schema import DatabaseSchemaEditor  # noqa: E402


# MySQL normally asks the live server which storage engine a table uses while
# deciding whether a foreign-key index is redundant. The export starts from an
# empty schema, so InnoDB is the safe equivalent and avoids that socket query.
def _offline_field_should_be_indexed(self, model, field):
    if not BaseDatabaseSchemaEditor._field_should_be_indexed(self, model, field):
        return False
    if field.get_internal_type() == "ForeignKey" and field.db_constraint:
        return False
    return not self._is_limited_data_type(field)


DatabaseSchemaEditor._field_should_be_indexed = _offline_field_should_be_indexed


def _offline_quote_value(self, value):
    # MySQL's normal schema editor delegates quoting to a live driver
    # connection. PyMySQL's pure converter produces the same literals offline.
    from pymysql.converters import escape_item, encoders
    return escape_item(value, "utf8mb4", encoders)


DatabaseSchemaEditor.quote_value = _offline_quote_value


HEADER = """-- ============================================================
--  Aurelia Collection · Hotel Booking & PMS
--  Current full structure + data export for Navicat
--  Target: MySQL 8+ / MariaDB 10.4+
--  Generated by scripts/export_mysql_kit_offline.py
--  In Navicat: create an empty database named `aurelia`, open it,
--  then right-click → Run SQL File… → pick this script.
-- ============================================================
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

"""


def schema_sql() -> str:
    """Collect every migration's MySQL DDL without opening a server socket."""
    db = connections["default"]
    # Passing None keeps MigrationLoader completely offline; it reads the
    # migration files and assumes an empty target instead of querying
    # django_migrations on a live MySQL server.
    loader = MigrationLoader(None, ignore_no_migrations=True)
    # Django normally learns these values from the server. Supplying safe
    # MySQL 8 defaults lets the schema editor choose MySQL column types
    # without opening a socket.
    db.__dict__["mysql_server_data"] = {
        "version": "8.0.36",
        "sql_mode": "STRICT_TRANS_TABLES",
        "default_storage_engine": "InnoDB",
        "sql_auto_is_null": False,
        "lower_case_table_names": False,
        "has_zoneinfo_database": True,
    }
    targets = loader.graph.leaf_nodes()
    state = ProjectState()
    # Enter with the backend's normal non-atomic setting (which does not open
    # a connection), then temporarily tell Migration.apply that it is safe to
    # skip per-operation transaction wrappers. Finally restore the flag before
    # leaving so the schema editor does not try to close a nonexistent socket.
    # Build the final ProjectState without executing database operations.
    # Creating the final models directly avoids historical ALTER TABLE steps
    # that normally inspect an existing live table.
    seen_nodes = set()
    for target in targets:
        for node in loader.graph.forwards_plan(target):
            if node in seen_nodes:
                continue
            seen_nodes.add(node)
            migration = loader.graph.nodes[node]
            for operation in migration.operations:
                operation.state_forwards(migration.app_label, state)

    editor = db.schema_editor(collect_sql=True)
    editor.__enter__()
    try:
        for model in state.apps.get_models():
            if not model._meta.auto_created and model._meta.managed:
                editor.create_model(model)
        # django_migrations is maintained by Django's migration recorder rather
        # than appearing in ProjectState.
        editor.collected_sql.append(
            "CREATE TABLE `django_migrations` ("
            "`id` bigint NOT NULL AUTO_INCREMENT, "
            "`app` varchar(255) NOT NULL, "
            "`name` varchar(255) NOT NULL, "
            "`applied` datetime(6) NOT NULL, "
            "PRIMARY KEY (`id`), UNIQUE KEY `django_migrations_app_name` (`app`,`name`)"
            ") ENGINE=InnoDB;"
        )
    finally:
        # collect_sql=True keeps deferred SQL in memory; do not execute it.
        editor.__exit__(None, None, None)
    return "\n".join(editor.collected_sql)


def main() -> int:
    output = ROOT / "navicat" / "aurelia_collection.mysql.sql"
    output.parent.mkdir(exist_ok=True)
    source = ROOT / "aurelia_collection.db"
    if not source.exists():
        print(f"[ERROR] SQLite source was not found: {source}")
        return 2
    connections.databases["source"] = {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": str(source),
        "USER": "", "PASSWORD": "", "HOST": "", "PORT": "",
        "CONN_MAX_AGE": 0, "CONN_HEALTH_CHECKS": False,
        "ATOMIC_REQUESTS": False, "AUTOCOMMIT": True,
        "TIME_ZONE": None, "OPTIONS": {"timeout": 30},
        "TEST": {"CHARSET": None, "COLLATION": None, "MIGRATE": True, "MIRROR": None, "NAME": None},
    }
    shutil.copy2(source, ROOT / "navicat" / "aurelia_collection.db")
    print("[OK] refreshed navicat/aurelia_collection.db")
    ddl = schema_sql()
    sql = HEADER + ddl + "\n\n" + data_sql("mysql", using="source")
    sql += "\n\nSET FOREIGN_KEY_CHECKS=1;\n"
    output.write_text(sql, encoding="utf-8")
    print(f"[OK] wrote {output}")
    print(f"     bytes: {output.stat().st_size}")
    print("     schema: collected from current Django migrations")
    print("     data:   copied from the configured SQLite database")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
