"""Exports a Navicat-ready database kit for the Aurelia Collection:

    navicat/aurelia_collection.db            (copy of the live SQLite file)
    navicat/aurelia_collection.postgres.sql  (full structure + data, PostgreSQL)
    navicat/aurelia_collection.mysql.sql     (full structure + data, MySQL/MariaDB)
    navicat/fixtures/aurelia_collection.json (Django fixtures, any backend)

Usage:  python3 scripts/export_navicat_kit.py

How it works
------------
Structure: a scratch database is migrated from zero for each vendor
(PostgreSQL / MySQL) and then schema-dumped with pg_dump / mysqldump. This
produces authoritative DDL that matches the Django models exactly (unlike
offline sqlmigrate replay, which cannot introspect and may miss index drops).
Data: rows are read from the live SQLite database via the ORM and emitted as
explicit-PK INSERTs in FK-topological order, with identity-sequence /
AUTO_INCREMENT repairs. django_migrations rows are included so the target
database counts as fully migrated (manage.py migrate becomes a no-op).

Requires locally running PostgreSQL and MySQL/MariaDB servers matching the
NAVICAT_DDL_VENDOR branches in config/settings.py (dev-time tool only).
"""
import datetime as dt
import decimal
import json
import os
import shutil
import subprocess
import sys
import uuid

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
OUT = os.path.join(ROOT, "navicat")
FIX = os.path.join(OUT, "fixtures")
os.makedirs(FIX, exist_ok=True)
sys.path.insert(0, ROOT)
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "config.settings")

import django  # noqa: E402

django.setup()

from django.apps import apps  # noqa: E402
from django.conf import settings  # noqa: E402
from django.core import serializers  # noqa: E402
from django.db import connection, connections, models  # noqa: E402

HEADER = """-- ============================================================
--  Aurelia Collection · Hotel Booking & PMS
--  Full structure + data export for Navicat ("Run SQL File…")
--  Target: {vendor}
--  Generated by scripts/export_navicat_kit.py
--  In Navicat: create an empty database named `aurelia`, open it,
--  then right-click → Run SQL File… → pick this script.
-- ============================================================
"""


# --------------------------------------------------------------------------
# literal rendering
# --------------------------------------------------------------------------
def q(text, vendor):
    if vendor == "mysql":
        escaped = (text.replace("\\", "\\\\").replace("'", "\\'")
                   .replace("\n", "\\n").replace("\r", "\\r")
                   .replace("\x00", "\\0").replace("\x1a", "\\Z"))
        return f"'{escaped}'"
    return "'" + text.replace("'", "''") + "'"


def sql_literal(value, vendor):
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return ("TRUE" if value else "FALSE") if vendor == "postgresql" else ("1" if value else "0")
    if isinstance(value, (int, float)):
        return repr(value)
    if isinstance(value, decimal.Decimal):
        return str(value)
    if isinstance(value, dt.datetime):
        s = (value.astimezone(dt.timezone.utc) if value.tzinfo else value).strftime("%Y-%m-%d %H:%M:%S")
        return f"'{s}'"
    if isinstance(value, (dt.date, dt.time)):
        return f"'{value.isoformat()}'"
    if isinstance(value, uuid.UUID):
        return f"'{value}'"
    if isinstance(value, (dict, list)):
        return q(json.dumps(value, ensure_ascii=False), vendor)
    if isinstance(value, (bytes, bytearray)):
        hexed = bytes(value).hex()
        return f"'\\x{hexed}'" if vendor == "postgresql" else f"X'{hexed}'"
    return q(str(value), vendor)


# --------------------------------------------------------------------------
# structure: fresh migrate into a scratch DB, then schema-dump
# --------------------------------------------------------------------------
def _run(cmd, env=None, **kw):
    out = subprocess.run(cmd, cwd=ROOT, env=env, capture_output=True, text=True, **kw)
    if out.returncode != 0:
        raise SystemExit(f"FAILED {' '.join(cmd)}\n{out.stdout[-2000:]}\n{out.stderr[-2000:]}")
    return out.stdout


def ddl_for(vendor):
    scratch = f"aurelia_ddl_{vendor[:2]}"
    env = dict(os.environ, NAVICAT_DDL_VENDOR=vendor, NAVICAT_DDL_NAME=scratch)
    if vendor == "postgresql":
        _run(["dropdb", "--if-exists", scratch])
        _run(["createdb", scratch])
        _run([sys.executable, "manage.py", "migrate", "--no-input"], env=env)
        ddl = _run(["pg_dump", "--schema-only", "--no-owner", "--no-privileges", scratch])
        _run(["dropdb", "--if-exists", scratch])
        # Make the dump Navicat-safe (no psql meta-commands) and keep a usable
        # search_path for the unqualified INSERTs in the data section.
        ddl = "\n".join(
            line for line in ddl.splitlines()
            if not line.startswith(("\\restrict", "\\unrestrict"))
        )
        ddl = ddl.replace("set_config('search_path', '', false)",
                          "set_config('search_path', 'public', false)")
    else:
        _run(["mysql", "-e", f"DROP DATABASE IF EXISTS {scratch}; CREATE DATABASE {scratch} CHARACTER SET utf8mb4;"])
        _run([sys.executable, "manage.py", "migrate", "--no-input"], env=env)
        ddl = _run(["mysqldump", "--no-data", "--skip-add-drop-table", scratch])
        _run(["mysql", "-e", f"DROP DATABASE IF EXISTS {scratch};"])
    return ddl


# --------------------------------------------------------------------------
# data: FK-topological model order, explicit-PK INSERTs
# --------------------------------------------------------------------------
def ordered_models():
    candidates = [m for m in apps.get_models()
                  if m._meta.managed and not m._meta.proxy and m._meta.concrete_model is m]
    pool = set(candidates)
    deps = {}
    for m in candidates:
        d = set()
        for f in m._meta.concrete_fields:  # forward FK/O2O columns only
            if f.is_relation and f.related_model is not None:
                rel = f.related_model._meta.concrete_model
                if rel in pool and rel is not m:
                    d.add(rel)
        deps[m] = d
    out, remaining = [], dict(deps)
    while remaining:
        ready = sorted((m for m, d in remaining.items() if d <= set(out)),
                       key=lambda m: (m._meta.app_label, m.__name__))
        if not ready:
            raise RuntimeError(f"dependency cycle among {list(remaining)}")
        out.extend(ready)
        for m in ready:
            remaining.pop(m)
    return out


def data_sql(vendor, using="default"):
    db = connections[using]
    lines = []
    if vendor == "postgresql":
        lines.append("SET search_path TO public;")
    if vendor == "mysql":
        lines += ["SET FOREIGN_KEY_CHECKS=0;", "SET NAMES utf8mb4;", ""]
    for model in ordered_models():
        objs = list(model.objects.using(using).all())
        table = model._meta.db_table
        cols = [f.column for f in model._meta.concrete_fields]
        if vendor == "mysql":
            quoted_table, col_list = f"`{table}`", ", ".join(f"`{c}`" for c in cols)
            lines.append(f"DELETE FROM `{table}`;")
        else:
            quoted_table, col_list = f'"{table}"', ", ".join(f'"{c}"' for c in cols)
            lines.append(f'TRUNCATE "{table}" RESTART IDENTITY CASCADE;')
        for obj in objs:
            vals = ", ".join(sql_literal(getattr(obj, f.attname), vendor)
                             for f in model._meta.concrete_fields)
            lines.append(f"INSERT INTO {quoted_table} ({col_list}) VALUES ({vals});")
        if isinstance(model._meta.pk, models.AutoField):
            pk = model._meta.pk.column
            if vendor == "postgresql":
                lines.append(f"SELECT setval(pg_get_serial_sequence('{table}', '{pk}'), "
                             f"COALESCE(MAX(\"{pk}\"), 1)) FROM \"{table}\";")
            else:
                lines.append(f"ALTER TABLE `{table}` AUTO_INCREMENT = 1;")
        lines.append("")
    # django_migrations has no app-registry model — export via raw SQL.
    with db.cursor() as cur:
        cur.execute("SELECT id, app, name, applied FROM django_migrations ORDER BY id")
        rows = cur.fetchall()
    if rows:
        if vendor == "mysql":
            lines.append("DELETE FROM `django_migrations`;")
            for r in rows:
                vals = ", ".join(sql_literal(v, vendor) for v in r)
                lines.append(f"INSERT INTO `django_migrations` (`id`, `app`, `name`, `applied`) VALUES ({vals});")
            lines.append("ALTER TABLE `django_migrations` AUTO_INCREMENT = 1;")
        else:
            lines.append('TRUNCATE "django_migrations" RESTART IDENTITY CASCADE;')
            for r in rows:
                vals = ", ".join(sql_literal(v, vendor) for v in r)
                lines.append(f'INSERT INTO "django_migrations" ("id", "app", "name", "applied") VALUES ({vals});')
            lines.append("SELECT setval(pg_get_serial_sequence('django_migrations', 'id'), "
                         "COALESCE(MAX(id), 1)) FROM django_migrations;")
    if vendor == "mysql":
        lines += ["", "SET FOREIGN_KEY_CHECKS=1;"]
    return "\n".join(lines)


# --------------------------------------------------------------------------
def _all_objects():
    for model in ordered_models():
        yield from model.objects.all()


def main():
    src = settings.DATABASES["default"]["NAME"]
    shutil.copy2(src, os.path.join(OUT, "aurelia_collection.db"))
    print("✓ navicat/aurelia_collection.db (SQLite — open directly in Navicat)")

    with open(os.path.join(FIX, "aurelia_collection.json"), "w", encoding="utf-8") as fh:
        serializers.serialize("json", _all_objects(), indent=2, stream=fh, ensure_ascii=False)
    print("✓ navicat/fixtures/aurelia_collection.json")

    for vendor, fname in [("postgresql", "aurelia_collection.postgres.sql"),
                          ("mysql", "aurelia_collection.mysql.sql")]:
        sql = (HEADER.format(vendor=vendor) + ddl_for(vendor)
               + "\n-- ---------- DATA ----------\n" + data_sql(vendor))
        with open(os.path.join(OUT, fname), "w", encoding="utf-8") as fh:
            fh.write(sql)
        print(f"✓ navicat/{fname} ({len(sql.splitlines())} lines)")


if __name__ == "__main__":
    main()
