"""Copy the current SQLite application data into an empty MySQL database.

The target database is selected with the normal MySQL environment variables:

    AURELIA_DB=mysql MYSQL_HOST=127.0.0.1 MYSQL_PORT=3306 \
    MYSQL_DATABASE=aurelia MYSQL_USER=root MYSQL_PASSWORD=SECRET \
    python scripts/migrate_sqlite_to_mysql.py --if-empty

The target schema is migrated first. Data is serialized through Django rather
than copied with SQLite-specific SQL, so dates, JSON, custom users, many-to-
many relations, bookings, folios, invoices, and payments are portable.

By default the command is safe to repeat: if the target already contains
properties or users it exits successfully without changing anything. Pass
--replace to flush the target first, or --source to choose another SQLite
file. The source database is never modified.
"""
from __future__ import annotations

import argparse
import os
import sys
import tempfile
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "config.settings")

import django  # noqa: E402


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--source",
        default=str(ROOT / "aurelia_collection.db"),
        help="SQLite source file (default: aurelia_collection.db)",
    )
    parser.add_argument(
        "--if-empty",
        action="store_true",
        help="skip cleanly when the MySQL target already has application data",
    )
    parser.add_argument(
        "--replace",
        action="store_true",
        help="flush the MySQL target before loading the SQLite snapshot",
    )
    args = parser.parse_args()

    if os.environ.get("AURELIA_DB", "").lower() != "mysql" and not (
        os.environ.get("MYSQL_DATABASE") or os.environ.get("MYSQL_DB")
    ):
        print("[ERROR] Set AURELIA_DB=mysql (or MYSQL_DATABASE) before running this command.")
        return 2

    source = Path(args.source).resolve()
    if not source.exists():
        print(f"[ERROR] SQLite source was not found: {source}")
        return 2
    if args.replace and args.if_empty:
        print("[ERROR] Choose --if-empty or --replace, not both.")
        return 2

    django.setup()

    from django.apps import apps
    from django.core import management, serializers
    from django.db import connections
    from django.db.utils import OperationalError

    # Add the SQLite source as a second Django connection while the default
    # connection remains the requested MySQL target.
    connections.databases["source"] = {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": str(source),
        "USER": "", "PASSWORD": "", "HOST": "", "PORT": "",
        "CONN_MAX_AGE": 0, "CONN_HEALTH_CHECKS": False,
        "ATOMIC_REQUESTS": False, "AUTOCOMMIT": True,
        "TIME_ZONE": None, "OPTIONS": {"timeout": 30},
        "TEST": {"CHARSET": None, "COLLATION": None, "MIGRATE": True, "MIRROR": None, "NAME": None},
    }

    try:
        management.call_command("migrate", database="default", interactive=False, verbosity=1)
    except Exception as exc:  # keep the connection error readable in a .bat window
        print(f"[ERROR] Could not migrate the MySQL target: {exc}")
        return 1

    from accounts.models import User
    from hotel.models import Property

    try:
        has_target_data = (
            Property.objects.using("default").exists()
            or User.objects.using("default").exists()
        )
    except OperationalError as exc:
        print(f"[ERROR] Could not inspect the MySQL target: {exc}")
        return 1

    if has_target_data and args.if_empty:
        print("[OK] MySQL target already contains application data; SQLite import skipped.")
        return 0
    if has_target_data and not args.replace:
        print("[ERROR] MySQL target is not empty. Re-run with --if-empty or --replace.")
        return 3
    if args.replace:
        print("  Flushing existing MySQL application data ...")
        management.call_command(
            "flush", database="default", interactive=False,
            load_initial_data=False, verbosity=0,
        )

    # Built-in content types and permissions are generated by migrate. They
    # are deliberately excluded from the snapshot to avoid duplicate natural
    # keys on the target. Project data, including the custom accounts.User,
    # is serialized in model order and loaddata resolves FK dependencies.
    excluded = {"contenttypes", "auth", "sessions", "admin"}
    models = [
        model for model in apps.get_models()
        if model._meta.app_label not in excluded
        and not model._meta.auto_created
        and not model._meta.proxy
    ]
    objects = (
        instance
        for model in models
        for instance in model._default_manager.using("source").all()
    )

    with tempfile.NamedTemporaryFile(
        mode="w", suffix=".json", prefix="aurelia-sqlite-to-mysql-", delete=False,
        encoding="utf-8",
    ) as fixture:
        fixture_path = Path(fixture.name)
        serializers.serialize(
            "json", objects, stream=fixture, indent=2,
            use_natural_foreign_keys=True, use_natural_primary_keys=True,
        )

    try:
        print(f"  Loading SQLite snapshot {source.name} into MySQL ...")
        management.call_command(
            "loaddata", str(fixture_path), database="default", verbosity=1,
        )
    except Exception as exc:
        print(f"[ERROR] MySQL data import failed: {exc}")
        return 1
    finally:
        fixture_path.unlink(missing_ok=True)

    print("[OK] SQLite data copied to MySQL successfully.")
    print(f"     Properties: {Property.objects.using('default').count()}")
    print(f"     Users:      {User.objects.using('default').count()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
