# Generated by Django 5.2.17 on 2026-09-08 09:11

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=24, unique=True)),
                ('guest_name', models.CharField(max_length=160)),
                ('guest_email', models.EmailField(blank=True, max_length=254)),
                ('guest_phone', models.CharField(blank=True, max_length=32)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('rooms_count', models.PositiveSmallIntegerField(default=1)),
                ('adults', models.PositiveSmallIntegerField(default=1)),
                ('children', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('checked_in', 'Checked in'), ('checked_out', 'Checked out'), ('cancelled', 'Cancelled'), ('no_show', 'No-show')], default='confirmed', max_length=16)),
                ('source', models.CharField(choices=[('web', 'Website'), ('phone', 'Phone'), ('walk_in', 'Walk-in'), ('ota', 'OTA / Agency')], default='web', max_length=10)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('nightly_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('service_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('tax_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('grand_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('rate_details', models.JSONField(blank=True, default=list, help_text='[{date, rate}] per night')),
                ('cancellation_reason', models.TextField(blank=True)),
                ('cancellation_fee', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('special_requests', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('guest', models.ForeignKey(blank=True, help_text='Null for walk-in reservations', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='hotel.roomtype')),
            ],
            options={
                'ordering': ['-check_in', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RateRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('rule_type', models.CharField(choices=[('seasonal', 'Seasonal range'), ('weekend', 'Weekend premium (Fri–Sat)'), ('promo', 'Promotion / discount')], default='seasonal', max_length=12)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('multiplier', models.DecimalField(decimal_places=3, help_text='1.250 = +25%, 0.850 = −15%', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.05'))])),
                ('priority', models.PositiveSmallIntegerField(default=0, help_text='Higher wins on conflicts')),
                ('is_active', models.BooleanField(default=True)),
                ('room_type', models.ForeignKey(blank=True, help_text='Blank = applies to all room types', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rate_rules', to='hotel.roomtype')),
            ],
            options={
                'ordering': ['-priority', 'start_date'],
            },
        ),
        migrations.CreateModel(
            name='RoomAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_assignments', to='bookings.booking')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='hotel.room')),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'check_in', 'check_out'], name='bookings_bo_status_f4db2d_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['room_type', 'check_in', 'check_out'], name='bookings_bo_room_ty_86afe5_idx'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('check_out__gt', models.F('check_in'))), name='booking_valid_range'),
        ),
        migrations.AddConstraint(
            model_name='raterule',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='rate_rule_valid_range'),
        ),
        migrations.AddConstraint(
            model_name='roomassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('released_at__isnull', True)), fields=('booking', 'room'), name='unique_active_assignment'),
        ),
    ]
