# Generated by Django 5.2.17 on 2026-09-08 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('hotel', '0002_property_roomtype_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='raterule',
            name='property',
            field=models.ForeignKey(blank=True, help_text='Blank = chain-wide; set for one hotel', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rate_rules', to='hotel.property'),
        ),
        migrations.AlterField(
            model_name='raterule',
            name='room_type',
            field=models.ForeignKey(blank=True, help_text='Blank = every room type in scope', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rate_rules', to='hotel.roomtype'),
        ),
    ]
