# Generated by Django 5.2.17 on 2026-09-27 09:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_raterule_property_alter_raterule_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='discount_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Welcome or promotion discount applied to room subtotal', max_digits=12),
        ),
    ]
